# Setup
title:               Taewoong Yoon
tagline:             'A lowly grad student'
description:         ''
url:                 https://twyoon.github.io/twyoon.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taewoong Yoon
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
